image: python:3

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - sphinx-build -a . public
  artifacts:
    paths:
    - public
